version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - "5000:5000" # Expose backend on port 5000
    volumes:
      - ./backend:/app # Mount the backend directory for development
    environment:
      - NODE_ENV=production
      - PORT=5000
    depends_on:
      - db # Backend depends on the database
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-service
    ports:
      - "3000:3000" # Expose frontend on port 3000
    volumes:
      - ./frontend:/app # Mount the frontend directory for development
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:5000 # URL for backend API
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: db-service
    ports:
      - "5432:5432" # Expose PostgreSQL on port 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data # Persistent database storage
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
