name: Build and Publish Docker Image

on:
  push:
    tags:
      - "v*"  # Trigger only on version tags, e.g., v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Extract version number from the tag
      - name: Extract version number
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t vivekgarg200/rapidtask:${{ env.VERSION }} ./backend
          docker tag vivekgarg200/rapidtask:${{ env.VERSION }} vivekgarg200/rapidtask:latest

      # Step 5: Push Docker image
      - name: Push Docker image
        run: |
          docker push vivekgarg200/rapidtask:${{ env.VERSION }}
          docker push vivekgarg200/rapidtask:latest
