name: Build and Publish Docker Image

on:
  push:
    tags:
      - "v*"
    paths:
      - "backend/**"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] 

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: matrix.os == 'ubuntu-latest' # Only required on Ubuntu

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version number
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t TheRdx04/rapidtask-engine:${{ env.VERSION }} ./backend
          docker tag TheRdx04/rapidtask-engine:${{ env.VERSION }} TheRdx04/rapidtask-engine:latest

      - name: Push Docker image
        run: |
          docker push TheRdx04/rapidtask-engine:${{ env.VERSION }}
          docker push TheRdx04/rapidtask-engine:latest
